datasource:
  url: jdbc:h2:tcp://localhost/~/test # db url
  driver-class-name: org.h2.Driver # db driver ???? url ??? ?? ???? ???
  username: hong
  password:
  schema: schema.sql # ddl file
  initialization-mode: always
  mybatis:
    mapper-location: mapper/**/*.xml # Mybatis mapper.xml 위치 설정
    type-aliases-package: org.example.demo.rest.domain #mapper에서 resultType 간략하게
    configuration:
      map-underscore-to-camel-case=true #java vo 클래스의 카멜케이서를 언더스코어로 바꾸어줌

logging:
  file:
    name: ${user.dir}/log/test.log  # 로깅 파일 위치이다.
  level:  # 각 package 별로 로깅 레벨을 지정할 수 있다.
    com.project.study : error
    com.project.study.controller : debug